// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: api/protocol/major.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Major struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ver   int32     `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Op    Operation `protobuf:"varint,2,opt,name=op,proto3,enum=im.protocol.Operation" json:"op,omitempty"`
	Seq   int64     `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Topic int32     `protobuf:"varint,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Body  []byte    `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Major) Reset() {
	*x = Major{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protocol_major_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Major) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Major) ProtoMessage() {}

func (x *Major) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_major_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Major.ProtoReflect.Descriptor instead.
func (*Major) Descriptor() ([]byte, []int) {
	return file_api_protocol_major_proto_rawDescGZIP(), []int{0}
}

func (x *Major) GetVer() int32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *Major) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_Heartbeat
}

func (x *Major) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Major) GetTopic() int32 {
	if x != nil {
		return x.Topic
	}
	return 0
}

func (x *Major) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_api_protocol_major_proto protoreflect.FileDescriptor

var file_api_protocol_major_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6d,
	0x61, 0x6a, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x05, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x65, 0x72,
	0x12, 0x26, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x69,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x42, 0x40, 0x0a, 0x0b, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x50, 0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x68, 0x6f, 0x79, 0x73, 0x69, 0x63, 0x73, 0x2f, 0x69, 0x6d, 0x2d, 0x6b, 0x69, 0x74,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protocol_major_proto_rawDescOnce sync.Once
	file_api_protocol_major_proto_rawDescData = file_api_protocol_major_proto_rawDesc
)

func file_api_protocol_major_proto_rawDescGZIP() []byte {
	file_api_protocol_major_proto_rawDescOnce.Do(func() {
		file_api_protocol_major_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protocol_major_proto_rawDescData)
	})
	return file_api_protocol_major_proto_rawDescData
}

var file_api_protocol_major_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_protocol_major_proto_goTypes = []interface{}{
	(*Major)(nil),  // 0: im.protocol.Major
	(Operation)(0), // 1: im.protocol.Operation
}
var file_api_protocol_major_proto_depIdxs = []int32{
	1, // 0: im.protocol.Major.op:type_name -> im.protocol.Operation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_protocol_major_proto_init() }
func file_api_protocol_major_proto_init() {
	if File_api_protocol_major_proto != nil {
		return
	}
	file_api_protocol_operation_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_protocol_major_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Major); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protocol_major_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protocol_major_proto_goTypes,
		DependencyIndexes: file_api_protocol_major_proto_depIdxs,
		MessageInfos:      file_api_protocol_major_proto_msgTypes,
	}.Build()
	File_api_protocol_major_proto = out.File
	file_api_protocol_major_proto_rawDesc = nil
	file_api_protocol_major_proto_goTypes = nil
	file_api_protocol_major_proto_depIdxs = nil
}
