// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: api/protocol/signal.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mode int32

const (
	Mode_Clients   Mode = 0
	Mode_Topic     Mode = 1
	Mode_Broadcast Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "Clients",
		1: "Topic",
		2: "Broadcast",
	}
	Mode_value = map[string]int32{
		"Clients":   0,
		"Topic":     1,
		"Broadcast": 2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protocol_signal_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_api_protocol_signal_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_api_protocol_signal_proto_rawDescGZIP(), []int{0}
}

var File_api_protocol_signal_proto protoreflect.FileDescriptor

var file_api_protocol_signal_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2a, 0x2d, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x10, 0x02, 0x42, 0x2d, 0x0a, 0x0b, 0x69, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x50, 0x01, 0x5a, 0x1c, 0x69, 0x6d, 0x2d, 0x6b, 0x69, 0x74,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protocol_signal_proto_rawDescOnce sync.Once
	file_api_protocol_signal_proto_rawDescData = file_api_protocol_signal_proto_rawDesc
)

func file_api_protocol_signal_proto_rawDescGZIP() []byte {
	file_api_protocol_signal_proto_rawDescOnce.Do(func() {
		file_api_protocol_signal_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protocol_signal_proto_rawDescData)
	})
	return file_api_protocol_signal_proto_rawDescData
}

var file_api_protocol_signal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protocol_signal_proto_goTypes = []interface{}{
	(Mode)(0), // 0: im.protocol.Mode
}
var file_api_protocol_signal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protocol_signal_proto_init() }
func file_api_protocol_signal_proto_init() {
	if File_api_protocol_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protocol_signal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protocol_signal_proto_goTypes,
		DependencyIndexes: file_api_protocol_signal_proto_depIdxs,
		EnumInfos:         file_api_protocol_signal_proto_enumTypes,
	}.Build()
	File_api_protocol_signal_proto = out.File
	file_api_protocol_signal_proto_rawDesc = nil
	file_api_protocol_signal_proto_goTypes = nil
	file_api_protocol_signal_proto_depIdxs = nil
}
